name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  update-readme:
    name: Update waka time.
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with: 
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
